# Part of the Crubit project, under the Apache License v2.0 with LLVM
# Exceptions. See /LICENSE for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

[package]
name = "crubit_support"
version = "0.1.0"
description = "Unified runtime support library for Crubit generated bindings."
edition.workspace = true
license-file.workspace = true
repository.workspace = true
categories.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]

[dev-dependencies]
googletest.workspace = true
