"""Disclaimer: This project is experimental, under heavy development, and should not
be used yet."""

load(":pipelined_compilation_test.bzl", "pipelined_compilation_test")

package(default_applicable_licenses = ["//third_party/crubit:license"])

licenses(["notice"])

pipelined_compilation_test(name = "pipelined_compilation")
