// Part of the Crubit project, under the Apache License v2.0 with LLVM
// Exceptions. See /LICENSE for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#ifndef THIRD_PARTY_CRUBIT_RS_BINDINGS_FROM_CC_TEST_STRUCT_INCOMPLETE_RECORD_REFERENCE_INCOMPLETE_RECORD_BY_VALUE_H_
#define THIRD_PARTY_CRUBIT_RS_BINDINGS_FROM_CC_TEST_STRUCT_INCOMPLETE_RECORD_REFERENCE_INCOMPLETE_RECORD_BY_VALUE_H_

struct A;
void FuncThatTakesAnIncompleteRecordByValue(A);

#endif  // THIRD_PARTY_CRUBIT_RS_BINDINGS_FROM_CC_TEST_STRUCT_INCOMPLETE_RECORD_REFERENCE_INCOMPLETE_RECORD_BY_VALUE_H_
