// Part of the Crubit project, under the Apache License v2.0 with LLVM
// Exceptions. See /LICENSE for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#ifndef CRUBIT_RS_BINDINGS_FROM_CC_TEST_BAZEL_UNIT_TESTS_ADDITIONAL_RUST_SRCS_FOR_CRUBIT_BINDINGS_ASPECT_HINT_TEST_EMPTY_H_
#define CRUBIT_RS_BINDINGS_FROM_CC_TEST_BAZEL_UNIT_TESTS_ADDITIONAL_RUST_SRCS_FOR_CRUBIT_BINDINGS_ASPECT_HINT_TEST_EMPTY_H_

#endif  // CRUBIT_RS_BINDINGS_FROM_CC_TEST_BAZEL_UNIT_TESTS_ADDITIONAL_RUST_SRCS_FOR_CRUBIT_BINDINGS_ASPECT_HINT_TEST_EMPTY_H_
