// Part of the Crubit project, under the Apache License v2.0 with LLVM
// Exceptions. See /LICENSE for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#[gtest]
fn test_build() {
    // Currently, the generated bindings of
    // `definition_forward_declared_template` doesn't compile: "cannot find
    // type `B` in crate `use_forward_declared_template`".
    // `definition_forward_declared_template` assumes type alias `B` is
    // successfully generated by `use_forward_declared_template`, but
    // `use_forward_declared_template` fails to do so because `B` references
    // a forward-declared type (whose definition is in
    // `definition_forward_declared_template`).
}
