"""Disclaimer: This project is experimental, under heavy development, and should not
be used yet."""

load(":cli_flag_aspect_hint_test.bzl", "rust_bindings_from_cc_cli_flag_aspect_hint_test_suite")

rust_bindings_from_cc_cli_flag_aspect_hint_test_suite(
    name = "rust_bindings_from_cc_cli_flag_aspect_hint_test_suite",
)
