// Part of the Crubit project, under the Apache License v2.0 with LLVM
// Exceptions. See /LICENSE for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#ifndef THIRD_PARTY_CRUBIT_RS_BINDINGS_FROM_CC_TEST_ASSUME_LIFETIMES_RELEASE_BLOCKLISTED_SUBPACKAGE_BLOCKLISTED_SUBSUBPACKAGE_EXPERIMENTAL_OPT_OUT_H_
#define THIRD_PARTY_CRUBIT_RS_BINDINGS_FROM_CC_TEST_ASSUME_LIFETIMES_RELEASE_BLOCKLISTED_SUBPACKAGE_BLOCKLISTED_SUBSUBPACKAGE_EXPERIMENTAL_OPT_OUT_H_

int& f(int& a);

#endif  // THIRD_PARTY_CRUBIT_RS_BINDINGS_FROM_CC_TEST_ASSUME_LIFETIMES_RELEASE_BLOCKLISTED_SUBPACKAGE_BLOCKLISTED_SUBSUBPACKAGE_EXPERIMENTAL_OPT_OUT_H_
