# Part of the Crubit project, under the Apache License v2.0 with LLVM
# Exceptions. See /LICENSE for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

filegroup(
    name = "extra_rs_srcs_for_cc_std",
    srcs = glob([
        "*.rs",
    ]),
    visibility = ["//:__subpackages__"],
)
