load(
    "//rs_bindings_from_cc/test/bazel_unit_tests:escape_cpp_target_name_test.bzl",
    "escape_cpp_target_name_test_suite",
)

package(default_applicable_licenses = ["//:license"])

escape_cpp_target_name_test_suite(name = "escape_cpp_target_name_test")
