# Part of the Crubit project, under the Apache License v2.0 with LLVM
# Exceptions. See /LICENSE for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

# Automatically @generated Cargo.toml for the Rust crate cc_bindings_from_rs_rustversion_impl.

[package]
name = "cc_bindings_from_rs_rustversion_impl"
edition.workspace = true

license-file.workspace = true
repository.workspace = true
categories.workspace = true

[lib]
proc-macro = true

path = "../../../cc_bindings_from_rs/rustversion_impl.rs"

doctest = false

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
