"""Disclaimer: This project is experimental, under heavy development, and should not
be used yet."""

load(":generating_files_test.bzl", "generating_files_test")

licenses(["notice"])

generating_files_test(name = "generating_files_test")
