// Part of the Crubit project, under the Apache License v2.0 with LLVM
// Exceptions. See /LICENSE for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

//! Support for retrieving Crubit control attributes. These attributes override
//! how Crubit handles a given AST entry.
//!
//! These should never be written directly by users, but rather generated by
//! Crubit itself. (Potentially in a procedural macro.)
#![feature(rustc_private)]
#![deny(rustc::internal)]

extern crate rustc_driver;
extern crate rustc_hir;
extern crate rustc_middle;
extern crate rustc_span;

use anyhow::{bail, ensure, Result};
use rustc_hir::def::DefKind;
use rustc_middle::ty::TyCtxt;
use rustc_span::def_id::DefId;
use rustc_span::symbol::Symbol;

/// A collection of attributes applied via `#[crubit_annotate::...]`.
///
/// Note that these attributes are procedural macros that generate doc comment attributes of the
/// form `#[doc="CRUBIT_ANNOTATE: ..."]`.
#[derive(Debug, Default, Clone, PartialEq)]
pub struct CrubitAttrs {
    /// The spelling of the C++ type of the item.
    ///
    /// For example, the following annotation indicates that the C++ type of
    /// this item should be `std::basic_string<char>`:
    ///
    ///   #[doc="CRUBIT_ANNOTATE: cpp_type=std::basic_string<char>"]
    pub cpp_type: Option<Symbol>,

    /// Paths to the header files that declare the type(s) used in `cpp_type`.
    ///
    /// If specified, these header files will be added as #include directives to
    /// the generated bindings.
    ///
    /// For example, the following annotation indicates that the C++ type of
    /// this item is `std::vector<Status>` and that it needs the headers `<vector>` and
    /// `status.h`:
    ///
    ///   #[doc="CRUBIT_ANNOTATE: cpp_type=std::vector<Status>"]
    ///   #[doc="CRUBIT_ANNOTATE: include_path=<vector>"]
    ///   #[doc="CRUBIT_ANNOTATE: include_path=status.h"]
    pub include_paths: Vec<Symbol>,

    /// Whether the annotated item is a specialization of another generic
    /// layout-compatible type. For example, `StatusOr<()>` mapping to C++ `absl::Status`.
    pub specializes_cpp_type: bool,

    /// The C++ name of the item. This allows us to rename Rust function names
    /// that are not C++-compatible like `new`.
    ///
    /// For instance, the following annotation indicates that the Rust function
    /// `new` should be renamed to `Create` in C++:
    ///
    /// ```
    /// #[doc="CRUBIT_ANNOTATE: cpp_name=Create"]
    /// pub fn new() -> i32 {...}
    /// ```
    pub cpp_name: Option<Symbol>,

    pub cpp_enum: Option<Symbol>,

    /// The name of a function that can convert the annotated Rust
    /// type into the C++ type specified in the `cpp_type` attribute.
    ///
    /// The generated bindings assume the function to be an `extern C` function
    /// with the following type signature:
    /// ```
    /// fn #rust_to_cpp_converter(rs_in: *const std::ffi::c_void, cpp_out: *mut std::ffi::c_void)
    /// ```
    /// `rs_in` is a valid pointer to an instance of the annotated Rust type.
    /// `cpp_out` is a valid pointer to uninitialized instance of
    /// `cpp_type`.
    pub rust_to_cpp_converter: Option<Symbol>,

    /// The name of a function that can convert the C++ type specified in the
    /// `cpp_type` attribute into the annotated Rust type.
    ///
    /// The generated bindings assume the function to be an `extern C` function
    /// with the following type signature:
    /// ```
    /// fn #cpp_to_rust_converter(cpp_in: *const std::ffi::c_void, rs_out: *mut std::ffi::c_void)
    /// ```
    /// `cpp_in` is a valid pointer to an instance of the C++ type specified in
    /// `cpp_type`. `rs_out` is a valid pointer to uninitialized instance of the
    /// annotated Rust Type.
    pub cpp_to_rust_converter: Option<Symbol>,

    /// The name of the Rust Crubit ABI that the type should be bridged as.
    pub bridge_abi_rust: Option<Symbol>,
    /// The name of the C++ Crubit ABI that the type should be bridged as.
    pub bridge_abi_cpp: Option<Symbol>,

    /// Whether the annotated item must be bound to C++.
    ///
    /// By default, when a given item does not receive bindings, it is replaced
    /// by a failure marker, such as a comment, which explains that bindings
    /// were not generated, and why. If this is true, then instead of replacing
    /// with a failure marker, bindings generation will fail outright at build time.
    ///
    /// This can be used to make failures more obvious, and occur earlier in the
    /// development process.
    ///
    /// For example, the following annotation indicates that the Rust function
    /// `new` must be bound to C++:
    ///
    /// ```
    /// #[crubit_annotate::must_bind]
    /// pub fn new() -> i32 {...}
    /// ```
    pub must_bind: bool,

    /// Whether the annotated item has the same ABI as the C++ type it maps to.
    pub same_abi: bool,

    /// Whether the annotated item corresponds to a C++-originated thread-safe type.
    pub cpp_thread_safe: bool,

    /// Whether the annotated item corresponds to a C++-originated move-constructible type.
    pub cpp_move_constructible: bool,

    /// Whether the annotated item should be skipped during C++ bindings generation.
    pub do_not_bind: bool,

    /// Whether the annotated struct's fields can be dropped in reverse order (e.g. from C++).
    pub field_drop_order_does_not_matter: bool,
}

impl CrubitAttrs {
    pub const CPP_TYPE: &'static str = "cpp_type";
    pub const CPP_NAME: &'static str = "cpp_name";
    pub const CPP_TYPE_INCLUDE: &'static str = "include_path";
    pub const CPP_ENUM: &'static str = "cpp_enum";
    pub const RUST_TO_CPP_CONVERTER: &'static str = "rust_to_cpp_converter";
    pub const CPP_TO_RUST_CONVERTER: &'static str = "cpp_to_rust_converter";
    pub const BRIDGE_ABI_RUST: &'static str = "bridge_abi_rust";
    pub const BRIDGE_ABI_CPP: &'static str = "bridge_abi_cpp";
    pub const MUST_BIND: &'static str = "must_bind";
    pub const SPECIALIZES_CPP_TYPE: &'static str = "specializes_cpp_type";
    pub const SAME_ABI: &'static str = "same_abi";
    pub const CPP_ORIGINATED_THREAD_SAFE: &'static str = "cpp_thread_safe";
    pub const CPP_MOVE_CONSTRUCTIBLE: &'static str = "cpp_move_constructible";
    pub const DO_NOT_BIND: &'static str = "do_not_bind";
    pub const FIELD_DROP_ORDER_DOES_NOT_MATTER: &'static str = "field_drop_order_does_not_matter";

    fn add_attr(&mut self, name: &str, symbol: Symbol) -> Result<()> {
        let set_opt_once = |slot: &mut Option<Symbol>, symbol: Symbol| -> Result<()> {
            ensure!(slot.is_none(), "Attribute {name} is specified more than once");
            *slot = Some(symbol);
            Ok(())
        };

        let set_bool_once = |slot: &mut bool| -> Result<()> {
            ensure!(!*slot, "Attribute {name} is specified more than once");
            *slot = true;
            Ok(())
        };

        match name {
            CrubitAttrs::CPP_TYPE => set_opt_once(&mut self.cpp_type, symbol)?,
            CrubitAttrs::CPP_NAME => set_opt_once(&mut self.cpp_name, symbol)?,
            CrubitAttrs::CPP_TYPE_INCLUDE => self.include_paths.push(symbol),
            CrubitAttrs::CPP_ENUM => set_opt_once(&mut self.cpp_enum, symbol)?,
            CrubitAttrs::RUST_TO_CPP_CONVERTER => {
                set_opt_once(&mut self.rust_to_cpp_converter, symbol)?
            }
            CrubitAttrs::CPP_TO_RUST_CONVERTER => {
                set_opt_once(&mut self.cpp_to_rust_converter, symbol)?
            }
            CrubitAttrs::BRIDGE_ABI_RUST => set_opt_once(&mut self.bridge_abi_rust, symbol)?,
            CrubitAttrs::BRIDGE_ABI_CPP => set_opt_once(&mut self.bridge_abi_cpp, symbol)?,
            CrubitAttrs::MUST_BIND => set_bool_once(&mut self.must_bind)?,
            CrubitAttrs::SPECIALIZES_CPP_TYPE => set_bool_once(&mut self.specializes_cpp_type)?,
            CrubitAttrs::SAME_ABI => set_bool_once(&mut self.same_abi)?,
            CrubitAttrs::CPP_ORIGINATED_THREAD_SAFE => set_bool_once(&mut self.cpp_thread_safe)?,
            CrubitAttrs::CPP_MOVE_CONSTRUCTIBLE => set_bool_once(&mut self.cpp_move_constructible)?,
            CrubitAttrs::DO_NOT_BIND => set_bool_once(&mut self.do_not_bind)?,
            CrubitAttrs::FIELD_DROP_ORDER_DOES_NOT_MATTER => {
                set_bool_once(&mut self.field_drop_order_does_not_matter)?
            }
            _ => bail!("Invalid CRUBIT_ANNOTATE key: \"{name}\""),
        }
        Ok(())
    }

    /// Returns the Crubit attributes that specify a bridging strategy,
    /// either composable, extern C function converters, or just a pointer case.
    ///
    /// Returns None if the attributes are not present.
    /// Returns an error if the attributes are present but malformed.
    pub fn get_bridging_attrs(&self) -> Result<Option<BridgingAttrs>> {
        match self {
            Self {
                cpp_type: Some(cpp_type),
                include_paths,
                cpp_to_rust_converter,
                rust_to_cpp_converter,
                bridge_abi_rust: None,
                bridge_abi_cpp: None,
                ..
            } => match (cpp_to_rust_converter, rust_to_cpp_converter) {
                (Some(cpp_to_rust_converter), Some(rust_to_cpp_converter)) => {
                    Ok(Some(BridgingAttrs::ExternCFuncConverters {
                        include_paths: include_paths.clone(),
                        cpp_type: *cpp_type,
                        cpp_to_rust_converter: *cpp_to_rust_converter,
                        rust_to_cpp_converter: *rust_to_cpp_converter,
                    }))
                }
                (None, None) => Ok(Some(BridgingAttrs::JustCppType {
                    include_paths: include_paths.clone(),
                    cpp_type: *cpp_type,
                })),
                _ => bail!(
                    "Invalid state of  #[crubit_annotate::...] attribute. \
                        Some, but not all, of cpp_to_rust_converter and rust_to_cpp_converter \
                        are set."
                ),
            },
            Self {
                cpp_type,
                cpp_to_rust_converter: None,
                rust_to_cpp_converter: None,
                bridge_abi_rust,
                bridge_abi_cpp,
                ..
            } => match (cpp_type, bridge_abi_rust, bridge_abi_cpp) {
                (Some(cpp_type), Some(abi_rust), Some(abi_cpp)) => {
                    Ok(Some(BridgingAttrs::Composable {
                        cpp_type: *cpp_type,
                        abi_rust: *abi_rust,
                        abi_cpp: *abi_cpp,
                    }))
                }
                (None, None, None) => Ok(None),
                _ => bail!(
                    "Invalid state of  #[crubit_annotate::...] attribute. \
                        Some, but not all, of cpp_type, bridge_abi_rust, and bridge_abi_cpp \
                        are set."
                ),
            },
            Self {
                cpp_type,
                cpp_to_rust_converter,
                rust_to_cpp_converter,
                bridge_abi_rust,
                bridge_abi_cpp,
                ..
            } => {
                let mut attrs = Vec::with_capacity(6);
                if cpp_type.is_some() {
                    attrs.push(CrubitAttrs::CPP_TYPE);
                }
                if cpp_to_rust_converter.is_some() {
                    attrs.push(CrubitAttrs::CPP_TO_RUST_CONVERTER);
                }
                if rust_to_cpp_converter.is_some() {
                    attrs.push(CrubitAttrs::RUST_TO_CPP_CONVERTER);
                }
                if bridge_abi_rust.is_some() {
                    attrs.push(CrubitAttrs::BRIDGE_ABI_RUST);
                }
                if bridge_abi_cpp.is_some() {
                    attrs.push(CrubitAttrs::BRIDGE_ABI_CPP);
                }
                ensure!(
                    attrs.is_empty(),
                    "Invalid state of  #[crubit_annotate::...] attribute. \
                        contains conflicting attributes: {attrs:?}"
                );
                Ok(None)
            }
        }
    }
}

/// An enum that separates out bridging attributes. Successful construction of
/// this type from `CrubitAttrs::get_bridging_attrs` indicates that the
/// attributes are valid and there are no conflicting attributes.
#[derive(Debug)]
pub enum BridgingAttrs {
    JustCppType {
        include_paths: Vec<Symbol>,
        cpp_type: Symbol,
    },
    ExternCFuncConverters {
        include_paths: Vec<Symbol>,
        cpp_type: Symbol,
        cpp_to_rust_converter: Symbol,
        rust_to_cpp_converter: Symbol,
    },
    Composable {
        /// The name of the C++ type that the annotated Rust type should be bridged
        /// to.
        cpp_type: Symbol,
        /// The name of the Rust Crubit ABI that the type should be bridged as.
        abi_rust: Symbol,
        /// The name of the C++ Crubit ABI that the type should be bridged as.
        abi_cpp: Symbol,
    },
}

// Ideally we could call https://github.com/rust-lang/rust/blob/2aaa62b89d22b570e560731b03e3d2d6f5c3bbce/compiler/rustc_metadata/src/rmeta/encoder.rs#L937 directly, but that method is not publicly available.
// It does not suffice to call `tcx.has_attrs` on our DefId because that will call `get_all_attrs` under the hood and panic if given an unsupported DefId.
#[rustversion::before(2026-07-11)]
pub fn supports_attrs(def_kind: DefKind) -> bool {
    // Const and AssocConst switch between unit variant and struct variant in nightly 2026-03-01. We
    // use a struct variant to cover both cases and supress the warning on versions where it's a
    // unit variant.
    #[allow(clippy::unneeded_struct_pattern)]
    match def_kind {
        DefKind::Mod
        | DefKind::Struct
        | DefKind::Union
        | DefKind::Enum
        | DefKind::Variant
        | DefKind::Trait
        | DefKind::TyAlias
        | DefKind::ForeignTy
        | DefKind::TraitAlias
        | DefKind::AssocTy
        | DefKind::Fn
        | DefKind::Const { .. }
        | DefKind::Static { nested: false, .. }
        | DefKind::AssocFn
        | DefKind::AssocConst { .. }
        | DefKind::Macro(_)
        | DefKind::Field
        | DefKind::Impl { .. }
        | DefKind::Closure => true,
        DefKind::SyntheticCoroutineBody
        | DefKind::TyParam
        | DefKind::ConstParam
        | DefKind::Ctor(..)
        | DefKind::ExternCrate
        | DefKind::Use
        | DefKind::ForeignMod
        | DefKind::AnonConst
        | DefKind::InlineConst
        | DefKind::OpaqueTy
        | DefKind::LifetimeParam
        | DefKind::Static { nested: true, .. }
        | DefKind::GlobalAsm => false,
    }
}

// Ideally we could call https://github.com/rust-lang/rust/blob/2aaa62b89d22b570e560731b03e3d2d6f5c3bbce/compiler/rustc_metadata/src/rmeta/encoder.rs#L937 directly, but that method is not publicly available.
// It does not suffice to call `tcx.has_attrs` on our DefId because that will call `get_all_attrs` under the hood and panic if given an unsupported DefId.
#[rustversion::since(2026-07-11)]
#[rustversion::before(2026-08-25)]
pub fn supports_attrs(def_kind: DefKind) -> bool {
    match def_kind {
        DefKind::Mod
        | DefKind::Struct
        | DefKind::Union
        | DefKind::Enum
        | DefKind::Variant
        | DefKind::Trait
        | DefKind::TyAlias
        | DefKind::ForeignTy
        | DefKind::TraitAlias
        | DefKind::AssocTy
        | DefKind::Fn
        | DefKind::Const { .. }
        | DefKind::Static { nested: false, .. }
        | DefKind::AssocFn
        | DefKind::AssocConst { .. }
        | DefKind::Macro(_)
        | DefKind::Field
        | DefKind::Impl { .. }
        | DefKind::Closure => true,
        DefKind::SyntheticCoroutineBody
        | DefKind::TyParam
        | DefKind::ConstParam
        | DefKind::Ctor(..)
        | DefKind::ExternCrate
        | DefKind::Use
        | DefKind::ForeignMod
        | DefKind::AnonConst
        | DefKind::OpaqueTy
        | DefKind::LifetimeParam
        | DefKind::Static { nested: true, .. }
        | DefKind::GlobalAsm => false,
    }
}

// Ideally we could call https://github.com/rust-lang/rust/blob/2aaa62b89d22b570e560731b03e3d2d6f5c3bbce/compiler/rustc_metadata/src/rmeta/encoder.rs#L937 directly, but that method is not publicly available.
// It does not suffice to call `tcx.has_attrs` on our DefId because that will call `get_all_attrs` under the hood and panic if given an unsupported DefId.
#[rustversion::since(2026-08-25)]
pub fn supports_attrs(def_kind: DefKind) -> bool {
    match def_kind {
        DefKind::Mod
        | DefKind::Struct
        | DefKind::Union
        | DefKind::Enum
        | DefKind::Variant
        | DefKind::Trait
        | DefKind::TyAlias
        | DefKind::ForeignTy
        | DefKind::TraitAlias
        | DefKind::AssocTy
        | DefKind::Fn
        | DefKind::Const { .. }
        | DefKind::Static { nested: false, .. }
        | DefKind::AssocFn
        | DefKind::AssocConst { .. }
        | DefKind::Macro(_)
        | DefKind::Field
        | DefKind::Impl { .. }
        | DefKind::Closure => true,
        DefKind::SyntheticCoroutineBody
        | DefKind::TyParam
        | DefKind::ConstParam
        | DefKind::Ctor(..)
        | DefKind::ExternCrate
        | DefKind::Use
        | DefKind::ForeignMod
        | DefKind::AnonConst
        | DefKind::OpaqueTy
        | DefKind::LifetimeParam
        | DefKind::Static { nested: true, .. }
        | DefKind::GlobalAsm
        | DefKind::TestBinderConstraints => false,
    }
}

/// Returns a CrubitAttrs object containing all the `#[doc="CRUBIT_ANNOTATE: key=value"]`
/// attributes of the specified definition.
pub fn get_attrs(tcx: TyCtxt, did: DefId) -> Result<CrubitAttrs> {
    let mut crubit_attrs = CrubitAttrs::default();
    if (!did.is_local() && tcx.crate_name(did.krate).as_str() == "core")
        // Calling get_all_attrs on an unsupported DefKind will panic, so we check beforehand.
        || !supports_attrs(tcx.def_kind(did))
    {
        // TODO: cramertj - calling `get_all_attrs` on `did` values from `core` crashes like:
        //
        // compiler/rustc_metadata/src/rmeta/decoder.rs:1396:17:
        // assertion `left == right` failed
        //   left: TypeNs("core")
        //   right: Ctor
        return Ok(crubit_attrs);
    }
    // This method has been deprecated to direct folks towards `find_attr!`. But our use case is not
    // met by `find_attr!`. There are no plans to remove the `get_all_attrs` method, so we silence
    // the warning here.
    #[allow(deprecated)]
    for attr in tcx.get_all_attrs(did) {
        let Some(comment) = attr.doc_str() else { continue };
        let Some((_, key_value)) = comment.as_str().split_once("CRUBIT_ANNOTATE:") else {
            continue;
        };
        let Some((key, value)) = key_value.split_once("=") else {
            bail!("Invalid CRUBIT_ANNOTATE attribute: `{comment}`. Expected `key=value`")
        };
        // Remove optional whitespace (e.g. `key = "value"` vs. `key="value"`).
        let key = key.trim();
        let value = value.trim();
        crubit_attrs.add_attr(key, Symbol::intern(value))?;
    }
    if crubit_attrs.do_not_bind {
        ensure!(
            matches!(tcx.def_kind(did), DefKind::Fn | DefKind::AssocFn),
            "`do_not_bind` is explicitly only permitted on functions and methods"
        )
    }
    if crubit_attrs.field_drop_order_does_not_matter {
        ensure!(
            matches!(tcx.def_kind(did), DefKind::Struct),
            "`field_drop_order_does_not_matter` is only permitted on structs"
        )
    }
    Ok(crubit_attrs)
}
