load(
    "//rs_bindings_from_cc/test/bazel_unit_tests/fission:fission_test.bzl",
    "fission_test_suite",
)

package(default_applicable_licenses = ["//:license"])

fission_test_suite(name = "fission_test_suite")
