// Part of the Crubit project, under the Apache License v2.0 with LLVM
// Exceptions. See /LICENSE for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#ifndef THIRD_PARTY_CRUBIT_RS_BINDINGS_FROM_CC_TEST_FORWARD_DECLARATION_MULTIPLE_FORWARD_DECLARATIONS_INDEPENDENT_DEFINITION_H_
#define THIRD_PARTY_CRUBIT_RS_BINDINGS_FROM_CC_TEST_FORWARD_DECLARATION_MULTIPLE_FORWARD_DECLARATIONS_INDEPENDENT_DEFINITION_H_

#pragma clang lifetime_elision

struct A final {};

#endif  // THIRD_PARTY_CRUBIT_RS_BINDINGS_FROM_CC_TEST_FORWARD_DECLARATION_MULTIPLE_FORWARD_INDEPENDENT_DECLARATIONS_DEFINITION_H_
