// Part of the Crubit project, under the Apache License v2.0 with LLVM
// Exceptions. See /LICENSE for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

// An API for resolving constraints on a pointer type's nullability that are
// implied by given safety constraints.
//
// Intended for use with a complete set of safety constraints generated by a
// SafetyConstraintGenerator.

#ifndef CRUBIT_NULLABILITY_INFERENCE_RESOLVE_CONSTRAINTS_H_
#define CRUBIT_NULLABILITY_INFERENCE_RESOLVE_CONSTRAINTS_H_

#include "nullability/inference/inference.proto.h"
#include "clang/Analysis/FlowSensitive/Value.h"
#include "llvm/ADT/DenseSet.h"

namespace clang::tidy::nullability {
// Resolve `SafetyConstraints` into implied constraints on the nullability
// annotation for the pointer declaration represented by `Pointer`.
//
// Requires that `Pointer` has null state properties as set by
// PointerNullabilityAnalysis.
NullabilityConstraint resolveConstraints(
    const llvm::DenseSet<const clang::dataflow::Formula *> &SafetyConstraints,
    const clang::dataflow::PointerValue &Pointer);
}  // namespace clang::tidy::nullability

#endif  // CRUBIT_NULLABILITY_INFERENCE_RESOLVE_CONSTRAINTS_H_
