// Part of the Crubit project, under the Apache License v2.0 with LLVM
// Exceptions. See /LICENSE for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#ifndef CRUBIT_RS_BINDINGS_FROM_CC_TEST_GENERATOR_COMMAND_LINE_USES_INCLUDE_PREFIX_H_
#define CRUBIT_RS_BINDINGS_FROM_CC_TEST_GENERATOR_COMMAND_LINE_USES_INCLUDE_PREFIX_H_

#endif  // CRUBIT_RS_BINDINGS_FROM_CC_TEST_GENERATOR_COMMAND_LINE_USES_INCLUDE_PREFIX_H_
