licenses(["notice"])

package(default_visibility = ["//third_party/crubit:__subpackages__"])

cc_library(
    name = "file_io",
    srcs = ["file_io.cc"],
    hdrs = ["file_io.h"],
    deps = [
        "@absl//status:statusor",
        "@llvm///llvm:Support",
    ],
)
