// Part of the Crubit project, under the Apache License v2.0 with LLVM
// Exceptions. See /LICENSE for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#ifndef THIRD_PARTY_CRUBIT_RS_BINDINGS_FROM_CC_TEST_GENERATED_HEADERS_GENERATED_HEADER_CONTENT_H_
#define THIRD_PARTY_CRUBIT_RS_BINDINGS_FROM_CC_TEST_GENERATED_HEADERS_GENERATED_HEADER_CONTENT_H_

inline int ReturnsFortyTwo() { return 42; }

#endif  // THIRD_PARTY_CRUBIT_RS_BINDINGS_FROM_CC_TEST_GENERATED_HEADERS_GENERATED_HEADER_CONTENT_H_
