// Part of the Crubit project, under the Apache License v2.0 with LLVM
// Exceptions. See /LICENSE for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#ifndef THIRD_PARTY_CRUBIT_RS_BINDINGS_FROM_CC_TEST_CPP_DUPLICATE_TARGET_NAME_SUBIDR1_SUBIDR1_A_H_
#define THIRD_PARTY_CRUBIT_RS_BINDINGS_FROM_CC_TEST_CPP_DUPLICATE_TARGET_NAME_SUBIDR1_SUBIDR1_A_H_

struct Subdir1A final {};

#endif  // THIRD_PARTY_CRUBIT_RS_BINDINGS_FROM_CC_TEST_CPP_DUPLICATE_TARGET_NAME_SUBIDR1_SUBIDR1_A_H_
