# Part of the Crubit project, under the Apache License v2.0 with LLVM
# Exceptions. See /LICENSE for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

module(
    name = "crubit_explorer",
    version = "0.1.0",
)

bazel_dep(name = "rules_rust", version = "0.71.3")
bazel_dep(name = "rules_license", version = "1.0.0")
bazel_dep(name = "rules_crubit")
local_path_override(
    module_name = "rules_crubit",
    path = "..",
)

crubit_toolchains = use_extension("@rules_crubit//bazel:extensions.bzl", "crubit_toolchains")
crubit_toolchains.configure(
    llvm_version = "22.1.0",
    rust_version = "nightly/2026-07-01",
)

register_toolchains("@rust_toolchains//:all", "@llvm_toolchain//:all")

use_repo(
    crubit_toolchains,
    "llvm_toolchain",
    "llvm_version_check",
    "rust_toolchains",
)

# Crate Universe to import dependencies from Cargo.toml
crate = use_extension("@rules_rust//crate_universe:extensions.bzl", "crate")
crate.from_cargo(
    name = "crubit_explorer_crates",
    cargo_lockfile = "//:Cargo.lock",
    manifests = ["//:Cargo.toml"],
)
use_repo(crate, "crubit_explorer_crates")
