load(":crubit_feature_hint_test.bzl", "crubit_feature_hint_test_suite")

package(default_applicable_licenses = ["//:license"])

crubit_feature_hint_test_suite(
    name = "crubit_feature_hint_test",
)
