# Part of the Crubit project, under the Apache License v2.0 with LLVM
# Exceptions. See /LICENSE for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
name: Crubit Nightly Test Matrix
on:
  workflow_dispatch:

jobs:
  use-test-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Use test matrix branch
        run: |
          echo "Use the nightly.yaml on the test-matrix branch. This nightly yaml exists because github only checks for the existence of actions on the main branch."
          exit 1