# Part of the Crubit project, under the Apache License v2.0 with LLVM
# Exceptions. See /LICENSE for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
name: Cargo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

# LINT.IfChange
jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      with:
        persist-credentials: false
    - name: Install protoc
      run: |
        PROTOC_VER=33.0
        curl -sSLO "https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VER}/protoc-${PROTOC_VER}-linux-x86_64.zip"
        sudo unzip -o "protoc-${PROTOC_VER}-linux-x86_64.zip" -d /usr/local
        rm "protoc-${PROTOC_VER}-linux-x86_64.zip"
    - name: Test Cargo project
      run: >
        cargo test --verbose --locked --workspace --no-fail-fast
        --exclude '*_sys'
        --exclude 'rs_bindings_from_cc*'
    - name: Build not-yet-testable Cargo crates
      run: >
        cargo build --verbose --locked --workspace
        --exclude '*_sys'
        --exclude=rs_bindings_from_cc
        --exclude=rs_bindings_from_cc_cc_api
        --exclude=rs_bindings_from_cc_cc_api_ffi
        --exclude=rs_bindings_from_cc_ir_matchers
        --exclude=rs_bindings_from_cc_ir_testing
        --exclude=rs_bindings_from_cc_multiplatform_ir_testing
        --exclude=rs_bindings_from_cc_test_generators

  test_cmake:

    runs-on: ubuntu-latest
    env:
      HAS_GCP_SA_KEY: ${{ secrets.GCP_SA_KEY && 'true' || 'false' }}
    strategy:
      matrix:
        project: [cmake, cmake_demo]

    steps:
    - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      with:
        persist-credentials: false
    - name: Authenticate to Google Cloud
      if: env.HAS_GCP_SA_KEY == 'true'
      id: auth
      uses: google-github-actions/auth@c200f3691d83b41bf9bbd8638997a462592937ed # v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    - name: Install sccache
      id: install_sccache
      if: env.HAS_GCP_SA_KEY == 'true'
      uses: mozilla-actions/sccache-action@65101d47ea8028ed0c98a1cdea8dd9182e9b5133 # v0.0.8
    - name: Test CMake project
      env:
        SCCACHE_GCS_BUCKET: crubit-ci-cmake
        SCCACHE_GCS_RW_MODE: READ_WRITE
        SCCACHE_GCS_KEY_PATH: ${{ steps.auth.outputs.credentials_file_path }}
        SCCACHE_GCS_KEY_PREFIX: sccache/${{ matrix.project }}
      run: |
        cd examples/build_systems/${{ matrix.project }}
        if [[ "$HAS_GCP_SA_KEY" == "true" ]]; then
          LAUNCHER_FLAGS="-DCMAKE_C_COMPILER_LAUNCHER=sccache -DCMAKE_CXX_COMPILER_LAUNCHER=sccache"
        else
          LAUNCHER_FLAGS=""
        fi
        cmake -B build -S . $LAUNCHER_FLAGS
        cmake --build build --parallel
        cd build
        ctest --output-on-failure --parallel 2
    - name: Show sccache stats
      if: steps.install_sccache.outcome == 'success' && always()
      run: sccache --show-stats

  test_bazel:

    runs-on: ubuntu-latest
    env:
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}

    steps:
    - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      with:
        persist-credentials: false
    - name: Authenticate to Google Cloud
      id: auth
      env:
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      if: ${{ env.GCP_SA_KEY != '' }}
      uses: google-github-actions/auth@c200f3691d83b41bf9bbd8638997a462592937ed # v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    - name: Setup Bazel
      uses: bazel-contrib/setup-bazel@c5acdfb288317d0b5c0bbd7a396a3dc868bb0f86 # 0.19.0
      with:
        bazelisk-cache: true
        disk-cache: ${{ github.workflow }}-${{ github.job }}
        repository-cache: true
    - name: Setup Bazel Remote Cache Flags
      id: bazel_cache_flags
      run: |
        if [[ -n "$GCP_SA_KEY" ]]; then
          echo "RCACHE_FLAGS=--remote_cache=https://storage.googleapis.com/crubit-ci-bazel --google_default_credentials" >> $GITHUB_ENV
          echo "Using GCS Remote Cache"
        else
          echo "RCACHE_FLAGS=" >> $GITHUB_ENV
          echo "Skipping GCS Remote Cache"
        fi
    - name: Build Bazel test project (example)
      run: |
        cd examples/build_systems/bazel
        bazelisk build ${RCACHE_FLAGS} //:main
# LINT.ThenChange(//depot/copy.bara.sky)
