# Part of the Crubit project, under the Apache License v2.0 with LLVM
# Exceptions. See /LICENSE for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
name: Cargo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

# LINT.IfChange
jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Test Cargo project
      run: >
        cargo test --verbose --locked --workspace --no-fail-fast
        --exclude '*_sys'
        --exclude 'rs_bindings_from_cc*'
    - name: Build not-yet-testable Cargo crates
      run: >
        cargo build --verbose --locked --workspace
        --exclude '*_sys'
        --exclude=rs_bindings_from_cc
        --exclude=rs_bindings_from_cc_cc_api
        --exclude=rs_bindings_from_cc_cc_api_ffi
        --exclude=rs_bindings_from_cc_ir_matchers
        --exclude=rs_bindings_from_cc_ir_testing
        --exclude=rs_bindings_from_cc_multiplatform_ir_testing
        --exclude=rs_bindings_from_cc_test_generators

  test_cmake:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Install ccache
      run: |
        curl -sL -o ccache.tar.xz https://github.com/ccache/ccache/releases/download/v4.13.6/ccache-4.13.6-linux-x86_64-glibc.tar.xz
        echo "508b2a1217dc6e04a23e967c7b95a0fb45d8a7e16fde9e180919698f2e2be060  ccache.tar.xz" | sha256sum --check
        sudo tar -xJf ccache.tar.xz -C /usr/local/bin --strip-components=1 ccache-4.13.6-linux-x86_64-glibc/ccache
    - name: Cache CMake with ccache
      uses: actions/cache@v5
      with:
        path: ~/.cache/ccache
        key: ${{ runner.os }}-ccache-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-ccache-
    - name: Test CMake project
      run: |
        cd examples/build_systems/cmake
        cmake -B build -S . -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
        cmake --build build --parallel
        cd build
        ctest --output-on-failure --parallel 2
# LINT.ThenChange(//depot/copy.bara.sky)
