"""Disclaimer: This project is experimental, under heavy development, and should not
be used yet."""

load(":namespaces_json_test.bzl", "namespaces_json_test")

licenses(["notice"])

namespaces_json_test(name = "namespaces_json")
